[package]
name = "Q3"
version = "0.1.0"
authors = ["Rao Hassan <raohassan4212@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"